const QuestionDatabasePL = [
    // --- POZIOM 1: Łatwe ---
    { q: "Kto jest pierwszym głównym bossem w Zamku Burzowego Całunu?", a: ["Margit", "Godrick", "Radahn", "Rennala"], correct: 1, difficulty: 1 },
    { q: "Jak nazywa się Twój wierzchowiec?", a: ["Strug", "Cień", "Torrent", "Duch"], correct: 0, difficulty: 1 },
    { q: "Jak nazywa się waluta w grze?", a: ["Dusze", "Runy", "Tętnice", "Złoto"], correct: 1, difficulty: 1 },
    { q: "Gdzie rezyduje wiedźma Ranni?", a: ["W Trzech Wieżach", "W Zamku Stormveil", "W Akademii", "W Caelid"], correct: 0, difficulty: 1 },
    { q: "Jak nazywa się centralny punkt (Hub) gracza?", a: ["Twierdza Okrągłego Stołu", "Kaplica Zgliszcz", "Majula", "Sen Łowcy"], correct: 0, difficulty: 1 },
    { q: "Kto daje Ci dzwonek do przyzywania duchów?", a: ["Melina", "Renna (Ranni)", "Roderika", "Hewg"], correct: 1, difficulty: 1 },
    { q: "Który atrybut odpowiada za pasek zdrowia?", a: ["Siła", "Wigor", "Zręczność", "Wiara"], correct: 1, difficulty: 1 },
    { q: "Jak nazywa się przedmiot używany do leczenia?", a: ["Butelka Szkarłatnych Łez", "Estus", "Krew", "Mikstura życia"], correct: 0, difficulty: 1 },
    { q: "Kto towarzyszy Ci na samym początku i oferuje 'układ'?", a: ["Ranni", "Melina", "Fia", "Hyetta"], correct: 1, difficulty: 1 },
    { q: "Jakie stworzenie pilnuje wejścia do Akademii Raya Lucaria?", a: ["Smok", "Olbrzym", "Pająk", "Rycerz"], correct: 0, difficulty: 1 },
    { q: "W jakim regionie zaczynasz grę?", a: ["Caelid", "Limgrave", "Liurnia", "Płaskowyż Altus"], correct: 1, difficulty: 1 },
    { q: "Co musisz zebrać, aby stać się Eldeńskim Lordem?", a: ["Wielkie Runy", "Pierścienie", "Dusze", "Odłamki gwiazd"], correct: 0, difficulty: 1 },
    { q: "Jak nazywa się kowal w Twierdzy Okrągłego Stołu?", a: ["Iji", "Hewg", "Andre", "Patches"], correct: 1, difficulty: 1 },
    { q: "Który atrybut jest kluczowy dla rzucania czarów (Sorceries)?", a: ["Wiara", "Inteligencja", "Zręczność", "Arcane"], correct: 1, difficulty: 1 },

    // --- POZIOM 2: Średnie ---
    { q: "Kto jest siostrą bliźniaczką Miquelli?", a: ["Malenia", "Ranni", "Marika", "Fia"], correct: 0, difficulty: 2 },
    { q: "Który boss jeździ na małym koniu o imieniu Leonard?", a: ["Godfrey", "Radahn", "Maliketh", "Rykard"], correct: 1, difficulty: 2 },
    { q: "Jak nazywa się kraina z dodatku DLC?", a: ["Kraina Cienia", "Otchłań", "Oolacile", "Malowany Świat"], correct: 0, difficulty: 2 },
    { q: "Kto jest Panem Krwi?", a: ["Morgott", "Mohg", "Miquella", "Malenia"], correct: 1, difficulty: 2 },
    { q: "Gdzie znajduje się Akademia Raya Lucaria?", a: ["W Limgrave", "W Caelid", "W Liurnii", "Na Płaskowyżu Altus"], correct: 2, difficulty: 2 },
    { q: "Który przedmiot pozwala na reset statystyk u Rennali?", a: ["Łuk Runy", "Łza Larwy", "Złota Runka", "Odłamek Kamienia Kowalskiego"], correct: 1, difficulty: 2 },
    { q: "Kto pilnuje wejścia do Stolicy (Leyndell) na moście?", a: ["Margit", "Strażnik Drzewa", "Smoczy Strażnik Drzewa", "Gideon"], correct: 2, difficulty: 2 },
    { q: "Jak nazywa się potężny wąż, który pożarł Rykarda?", a: ["Jormungandr", "Wąż Pożerający Bogów", "Ezykeel", "Messmer"], correct: 1, difficulty: 2 },
    { q: "Który z wymienionych regionów jest opanowany przez Szkarłatną Zgniliznę?", a: ["Limgrave", "Caelid", "Liurnia", "Góra Gelmir"], correct: 1, difficulty: 2 },
    { q: "Kogo spotykasz wewnątrz słoika (Wielki Słoik)?", a: ["Patchesa", "Alexandra", "Blaidda", "Iji"], correct: 1, difficulty: 2 },
    { q: "Jak nazywa się miecz, który dzierży Maliketh?", a: ["Rzeki Krwi", "Ostrze Przeznaczonej Śmierci", "Księżycowy miecz", "Złoty porządek"], correct: 1, difficulty: 2 },
    { q: "Kto jest matką wszystkich półbogów?", a: ["Rennala", "Marika", "Ranni", "Fia"], correct: 1, difficulty: 2 },
    { q: "Jak nazywa się magiczne miasto w Caelid?", a: ["Sellia", "Ordina", "Nokron", "Leyndell"], correct: 0, difficulty: 2 },
    { q: "Który NPC 'nieustannie' Cię zdradza (tradycja serii)?", a: ["Patches", "Gideon", "Varre", "Dung Eater"], correct: 0, difficulty: 2 },

    // --- POZIOM 3: Trudne ---
    { q: "Jak brzmiało prawdziwe imię Pierwszego Eldeńskiego Lorda?", a: ["Godwyn", "Hoarah Loux", "Radagon", "Morgott"], correct: 1, difficulty: 3 },
    { q: "Kto uknuł Noc Czarnych Noży?", a: ["Marika", "Ranni", "Malenia", "Melina"], correct: 1, difficulty: 3 },
    { q: "Jak nazywa się zewnętrzny bóg, któremu służy Mohg?", a: ["Wielka Wola", "Bezkresna Matka", "Oszalały Płomień", "Bóg Zgnilizny"], correct: 1, difficulty: 3 },
    { q: "Kto był mentorem Malenii, który nauczył ją tańca miecza?", a: ["Niewidomy Szermierz", "Radagon", "Godfrey", "Maliketh"], correct: 0, difficulty: 3 },
    { q: "Jak nazywa się bestia, która jest cieniem królowej Mariki?", a: ["Blaidd", "Maliketh", "Serosh", "Gurranq"], correct: 1, difficulty: 3 },
    { q: "Który przedmiot jest niezbędny, by wejść do Krainy Cienia (DLC)?", a: ["Runa Morgotta", "Ręka Miquelli", "Oko Mariki", "Serce Smoka"], correct: 1, difficulty: 3 },
    { q: "Kto stworzył Zakon Złotej Maski?", a: ["Złota Maska", "Corhyn", "Gideon", "Miriel"], correct: 0, difficulty: 3 },
    { q: "Jak nazywa się statek/byt, który zesłała Wielka Wola na Ziemie Pomiędzy?", a: ["Eldeńska Bestia", "Metyr", "Astel", "Elden Ring"], correct: 0, difficulty: 3 },
    { q: "Kto jest ojcem Miquelli i Malenii?", a: ["Godfrey", "Radagon", "Placidusax", "Rykard"], correct: 1, difficulty: 3 },
    { q: "Jak nazywa się miasto wieczne ukryte pod ziemią?", a: ["Nokron", "Sellia", "Ordina", "Leyndell"], correct: 0, difficulty: 3 },
    { q: "Kto jest pierwszą linią obrony przed Elden Ringiem (Finałowa walka)?", a: ["Radagon", "Godfrey", "Marika", "Gideon"], correct: 0, difficulty: 3 },
    { q: "Jak nazywa się matka Palców (Mother of Fingers) w DLC?", a: ["Metyr", "Nanaya", "Romina", "Marika"], correct: 0, difficulty: 3 },
    { q: "Który z półbogów został 'pożarty' przez węża dobrowolnie?", a: ["Rykard", "Radahn", "Godrick", "Mohg"], correct: 0, difficulty: 3 },
    { q: "Jak nazywa się kraina, z której pochodził Godfrey (Hoarah Loux)?", a: ["Badlands", "Land of Reeds", "Zamorskie kraje", "Otchłań"], correct: 0, difficulty: 3 }
];

const QuestionDatabaseEN = [
    // --- LEVEL 1 ---
    { q: "Who is the first main boss in Stormveil Castle?", a: ["Margit", "Godrick", "Radahn", "Rennala"], correct: 1, difficulty: 1 },
    { q: "What is the name of your steed?", a: ["Torrent", "Shadow", "Spirit", "Torrentia"], correct: 0, difficulty: 1 },
    { q: "What is the currency used in the game?", a: ["Souls", "Runes", "Blood Echoes", "Gold"], correct: 1, difficulty: 1 },
    { q: "Where does Ranni the Witch reside?", a: ["Three Sisters", "Stormveil Castle", "Academy", "Caelid"], correct: 0, difficulty: 1 },
    { q: "What is the main hub for the player called?", a: ["Roundtable Hold", "Chapel of Anticipation", "Majula", "Hunter's Dream"], correct: 0, difficulty: 1 },
    { q: "Who gives you the Spirit Calling Bell?", a: ["Melina", "Renna (Ranni)", "Roderika", "Hewg"], correct: 1, difficulty: 1 },
    { q: "Which attribute corresponds to your health bar?", a: ["Strength", "Vigor", "Dexterity", "Faith"], correct: 1, difficulty: 1 },
    { q: "What is the primary item used for healing?", a: ["Flask of Crimson Tears", "Estus", "Blood", "Health Potion"], correct: 0, difficulty: 1 },
    { q: "Who offers you an 'accord' at the beginning of the game?", a: ["Ranni", "Melina", "Fia", "Hyetta"], correct: 1, difficulty: 1 },
    { q: "What creature guards the entrance to Raya Lucaria Academy?", a: ["Dragon", "Giant", "Spider", "Knight"], correct: 0, difficulty: 1 },
    { q: "In which region do you start the game?", a: ["Caelid", "Limgrave", "Liurnia", "Altus Plateau"], correct: 1, difficulty: 1 },
    { q: "What must you gather to become Elden Lord?", a: ["Great Runes", "Rings", "Souls", "Starlight Shards"], correct: 0, difficulty: 1 },
    { q: "What is the blacksmith's name in Roundtable Hold?", a: ["Iji", "Hewg", "Andre", "Patches"], correct: 1, difficulty: 1 },
    { q: "Which attribute is key for casting Sorceries?", a: ["Faith", "Intelligence", "Dexterity", "Arcane"], correct: 1, difficulty: 1 },

    // --- LEVEL 2 ---
    { q: "Who is Miquella's twin sister?", a: ["Malenia", "Ranni", "Marika", "Fia"], correct: 0, difficulty: 2 },
    { q: "Which boss rides a small horse named Leonard?", a: ["Godfrey", "Radahn", "Maliketh", "Rykard"], correct: 1, difficulty: 2 },
    { q: "What is the name of the DLC land?", a: ["Land of Shadow", "The Abyss", "Oolacile", "Painted World"], correct: 0, difficulty: 2 },
    { q: "Who is the Lord of Blood?", a: ["Morgott", "Mohg", "Miquella", "Malenia"], correct: 1, difficulty: 2 },
    { q: "Where is Raya Lucaria Academy located?", a: ["Limgrave", "Caelid", "Liurnia", "Altus Plateau"], correct: 2, difficulty: 2 },
    { q: "Which item allows you to reset stats with Rennala?", a: ["Rune Arc", "Larval Tear", "Golden Rune", "Smithing Stone"], correct: 1, difficulty: 2 },
    { q: "Who guards the Leyndell entrance on the bridge?", a: ["Margit", "Tree Sentinel", "Draconic Tree Sentinel", "Gideon"], correct: 2, difficulty: 2 },
    { q: "What is the name of the serpent that devoured Rykard?", a: ["Jormungandr", "God-Devouring Serpent", "Ezykeel", "Messmer"], correct: 1, difficulty: 2 },
    { q: "Which region is infested with Scarlet Rot?", a: ["Limgrave", "Caelid", "Liurnia", "Mt. Gelmir"], correct: 1, difficulty: 2 },
    { q: "Who do you meet inside a Great Jar?", a: ["Patches", "Alexander", "Blaidd", "Iji"], correct: 1, difficulty: 2 },
    { q: "What is the name of the blade Maliketh wields?", a: ["Rivers of Blood", "Destined Death", "Moonlight Blade", "Golden Order"], correct: 1, difficulty: 2 },
    { q: "Who is the mother of all demigods?", a: ["Rennala", "Marika", "Ranni", "Fia"], correct: 1, difficulty: 2 },
    { q: "What is the name of the magic city in Caelid?", a: ["Sellia", "Ordina", "Nokron", "Leyndell"], correct: 0, difficulty: 2 },
    { q: "Which NPC 'constantly' betrays you (series tradition)?", a: ["Patches", "Gideon", "Varre", "Dung Eater"], correct: 0, difficulty: 2 },

    // --- LEVEL 3 ---
    { q: "What was the true name of the first Elden Lord?", a: ["Godwyn", "Hoarah Loux", "Radagon", "Morgott"], correct: 1, difficulty: 3 },
    { q: "Who plotted the Night of the Black Knives?", a: ["Marika", "Ranni", "Malenia", "Melina"], correct: 1, difficulty: 3 },
    { q: "Which Outer God does Mohg serve?", a: ["Greater Will", "Formless Mother", "Frenzied Flame", "Rot God"], correct: 1, difficulty: 3 },
    { q: "Who was Malenia's mentor that taught her the sword dance?", a: ["Blind Swordsman", "Radagon", "Godfrey", "Maliketh"], correct: 0, difficulty: 3 },
    { q: "What is the name of the beast that is Queen Marika's shadow?", a: ["Blaidd", "Maliketh", "Serosh", "Gurranq"], correct: 1, difficulty: 3 },
    { q: "Which item is necessary to enter the Land of Shadow (DLC)?", a: ["Morgott's Rune", "Miquella's Arm", "Marika's Eye", "Dragon Heart"], correct: 1, difficulty: 3 },
    { q: "Who created the Golden Mask's Order?", a: ["Goldmask", "Corhyn", "Gideon", "Miriel"], correct: 0, difficulty: 3 },
    { q: "What is the being sent by the Greater Will to the Lands Between?", a: ["Elden Beast", "Metyr", "Astel", "Elden Ring"], correct: 0, difficulty: 3 },
    { q: "Who is the father of Miquella and Malenia?", a: ["Godfrey", "Radagon", "Placidusax", "Rykard"], correct: 1, difficulty: 3 },
    { q: "What is the name of the Eternal City hidden underground?", a: ["Nokron", "Sellia", "Ordina", "Leyndell"], correct: 0, difficulty: 3 },
    { q: "Who is the first line of defense before the Elden Ring (Final battle)?", a: ["Radagon", "Godfrey", "Marika", "Gideon"], correct: 0, difficulty: 3 },
    { q: "What is the name of the Mother of Fingers in the DLC?", a: ["Metyr", "Nanaya", "Romina", "Marika"], correct: 0, difficulty: 3 },
    { q: "Which demigod was 'devoured' by the serpent voluntarily?", a: ["Rykard", "Radahn", "Godrick", "Mohg"], correct: 0, difficulty: 3 },
    { q: "What is the name of the land Godfrey (Hoarah Loux) came from?", a: ["Badlands", "Land of Reeds", "Land Across the Sea", "The Abyss"], correct: 0, difficulty: 3 }
];